PUT https://localhost:7086/breakfasts/1a160ec1-4329-484e-af87-7fddd89ae337
Content-Type: application/json

{
    "name": "Vegan Sunshine 25",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "sasa"
    ],
    "Sweet": [
        "Cookie"
    ]
}