PUT https://localhost:7086/breakfasts/5b1ec44f-cc4f-41ae-8235-3cfe04a21739
Content-Type: application/json

{
    "name": "Vegan Sunshine 2",
    "description": "Vegan everything! Join us for a healthy breakfast..lorem ipsum dolor sit amet",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "sasa"
    ],
    "Sweet": [
        "Cookie"
    ]
}